# Generated by Django 5.0.1 on 2024-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Geral'), ('preferências', 'Preferências'), ('política', 'Política')], default=None, max_length=15, null=True, verbose_name='Categoria'),
        ),
    ]
